import { auth } from "../_lib/auth";

export const metadata = {
  title: "Account",
  description: "Generated by Next.js",
};

async function page() {
  const session = await auth();

  return (
    <h2 className="font-semibold text-2xl text-accent-400 mb-7 capitalize">
      Welcome {session.user.name.split(" ")[0]}
    </h2>
  );
}

export default page;
