import Logo from "@/app/_components/Logo";
import Navigation from "@/app/_components/Navigation ";

import "@/app/_styles/globals.css";

import { Josefin_Sans } from "next/font/google";
import Header from "./_components/Header";
import { ReservationProvider } from "./_components/ReservationContext";
const josefin = Josefin_Sans({ subsets: ["latin"], display: "swap" });

export const metadata = {
  // title: "The Wild Oasis",
  title: { template: "%s/The wild Oasis", default: "Welcome / The wild Oasis" },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} bg-primary-950 text-primary-50 min-h-screen flex flex-col relative`}
      >
        <Header />
        <div className="flex flex-1">
          <main className="max-w-7xl mx-auto px-8 py-5 w-full">
            <ReservationProvider>{children}</ReservationProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
